python3 train.py \
    --device gpu \
    --output_path output \
    --lr 3e-5 \
    --dropout 0.1 \
    --epochs 2 \
    --batch_size_train 64 \
    --batch_size_eval 256 \
    --num_workers 0 \
    --eval_step 10 \
    --max_len 64 \
    --seed 3272 \
    --train_file data/nli_for_simcse.csv \
    --dev_file data/stsbenchmark/sts-dev.csv \
    --test_file data/stsbenchmark/sts-test.csv \
    --pretrain_model_path pretrain_model/unsup-simcse-bert-base-uncased \
    --pooler cls \
    --train_mode supervise \
    --do_train \
    --do_predict \
    # --overwrite_cache \